# -*- coding: utf-8 -*-
"""homework2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A4cziMLIQz3axT9tMK9m8xNg-yMSer7t

#CIS 5200: Machine Learning Homework 2
"""

import os
import sys

# For autograder only, do not modify this cell.
# True for Google Colab, False for autograder
NOTEBOOK = (os.getenv('IS_AUTOGRADER') is None)
if NOTEBOOK:
    print("[INFO, OK] Google Colab.")
else:
    print("[INFO, OK] Autograder.")
    sys.exit()

# %%capture
!pip install penngrader-client

# Commented out IPython magic to ensure Python compatibility.
# %%writefile config.yaml
# grader_api_url: "https://yj0vsrf8l4.execute-api.us-east-1.amazonaws.com/Initial/TestSandbox"
# grader_api_key: "dBB5ucuV5L6GyKFKmlrfP4bKkhtnA0bP42lR3rSh"
# token_generator_url: "https://yj0vsrf8l4.execute-api.us-east-1.amazonaws.com/Initial/GetTokens"
# token_generator_api_key: "dBB5ucuV5L6GyKFKmlrfP4bKkhtnA0bP42lR3rSh"

from penngrader.grader import PennGrader

# PLEASE ENSURE YOUR PENN-ID IS ENTERED CORRECTLY. IF NOT, THE AUTOGRADER WON'T KNOW WHO
# TO ASSIGN POINTS TO YOU IN OUR BACKEND
STUDENT_ID = 47257339 # YOUR PENN-ID GOES HERE AS AN INTEGER #
SECRET = STUDENT_ID
HW_ID = 2

grader = PennGrader('config.yaml', HW_ID, STUDENT_ID, SECRET, "cis5200_spr26")

# Commented out IPython magic to ensure Python compatibility.
import torch
import torch.nn.functional as F
import torch.nn as nn

from sklearn import datasets
import cvxpy as cp

from PIL import Image
from dill.source import getsource

import matplotlib
# %matplotlib inline
import matplotlib.pyplot as plt

def get_class_source(cls):
    import re
    class_name = cls.__name__
    from IPython import get_ipython
    ipython = get_ipython()
    inputs = ipython.user_ns['In']
    pattern = re.compile(r'^\s*class\s+{}\b'.format(class_name))
    for cell in reversed(inputs):
        if pattern.search(cell):
            return cell
    return None

"""# Dataset: Wine Quality Prediction

Some research on blind wine tasting has suggested that [people cannot taste the difference between ordinary and pricy wine brands](https://phys.org/news/2011-04-expensive-inexpensive-wines.html). Indeed, even experienced tasters may be as consistent as [random numbers](https://www.seattleweekly.com/food/wine-snob-scandal/). Is professional wine tasting in shambles? Maybe ML can take over.

In this problem set, we will train some simple linear models to predict wine quality. We'll be using the data from [this repository](https://archive.ics.uci.edu/ml/datasets/Wine+Quality) for both the classification and regression tasks. The following cells will download and set up the data for you.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !wget https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv
# !wget https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv
# !wget https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality.names

from sklearn.model_selection import train_test_split
import pandas as pd
import torch

red_df = pd.read_csv('winequality-red.csv', delimiter=';')

X = torch.from_numpy(red_df.drop(columns=['quality']).to_numpy())
y = torch.from_numpy(red_df['quality'].to_numpy())

# Split data into train/test splits
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# Normalize the data to have zero mean and standard deviation,
# and add bias term
mu, sigma = X_train.mean(0), X_train.std(0)
X_train, X_test = [ torch.cat([((x-mu)/sigma).float(), torch.ones(x.size(0),1)], dim=1)
                    for x in [X_train, X_test]]

# Transform labels to {-1,1} for logistic regression
y_binary_train, y_binary_test = [ (torch.sign(y - 5.5)).long()
                                  for y in [y_train, y_test]]
y_regression_train, y_regression_test = [ y.float() for y in [y_train, y_test]]

"""#1. Logistic Regression
In this first problem, you will implement a logistic regression classifier to classify good wine (y=1) from bad wine (y=0). Your professor has arbitrarily decided that good wine has a score of at least 5.5. The classifier is split into the following components:

Loss (3pts) & gradient (3pts) - given a batch of examples  
X
  and labels  
y
  and weights for the logistic regression classifier, compute the batched logistic loss and gradient of the loss with with respect to the model parameters  
w
 . Note that this is slightly different from the gradient in Homework 0, which was with respect to the sample  
X
 .
Fit (2pt) - Given a loss function and data, find the weights of an optimal logistic regression model that minimizes the logistic loss
Predict (3pts) - Given the weights of a logistic regression model and new data, predict the most likely class
We provide an generic gradient-based optimizer for you which minimizes the logistic loss function, you can call it with LogisticOptimizer().optimize(X,y). It does not need any parameter adjustment.

Hint: The optimizer will minimize the logistic loss. So this value of this loss should be decreasing over iterations
"""

def logistic_loss(X, y, w):
    # Given a batch of samples and labels, and the weights of a logistic
    # classifier, compute the batched logistic loss.
    #
    # X := Tensor(float) of size (m,d) --- This is a batch of m examples of
    #     of dimension d
    #
    # y := Tensor(int) of size (m,) --- This is a batch of m labels in {-1,1}
    #
    # w := Tensor(float) of size(d,) --- This is the weights of a logistic
    #     classifer.
    #
    # Return := Tensor of size (m,) --- This is the logistic loss for each
    #     example.

    # Fill in the rest
    loss = torch.log(1+torch.exp(-y * (X @ w)))
    return loss

def logistic_gradient(X, y, w):
    # Given a batch of samples and labels, compute the batched gradient of
    # the logistic loss.
    #
    # X := Tensor(float) of size (m,d) --- This is a batch of m examples of
    #     of dimension d
    #
    # y := Tensor(int) of size (m,) --- This is a batch of m labels in {-1,1}
    #
    # w := Tensor(float) of size(d,) --- This is the weights of a logistic
    #     classifer.
    #
    # Return := Tensor of size (m,) --- This is the logistic loss for each
    #     example.
    #
    # Hint: A very similar gradient was calculated in Homework 0.
    # However, that was the sample gradient (with respect to X), whereas
    # what we need here is the parameter gradient (with respect to w).

    # Fill in the rest
    grad=(-y / (1+torch.exp(y * (X @ w))))[:,None]*X
    return grad

def optimize(X, y, niters=100):
    # Given a dataset of examples and labels, minimizes the logistic loss
    # using standard gradient descent.
    #
    # This optimizer is written for you, and you only need to implement the
    # logistic loss and gradient functions above.
    #
    # X := Tensor(float) of size (m,d) --- This is a batch of m examples of
    #     of dimension d
    #
    # y := Tensor(int) of size (m,) --- This is a batch of m labels in {-1,1}
    #
    # Return := Tensor of size(d,) --- This is the fitted weights of a
    #     logistic regression model

    m,d = X.size()
    w = torch.zeros(d)
    print('Optimizing logistic function...')
    for i in range(niters):
        loss = logistic_loss(X,y,w).mean()
        grad = logistic_gradient(X,y,w).mean(0)
        w -= grad
        if i % 50 == 0:
            print(i, loss.item())
    print('Optimizing done.')
    return w

def logistic_fit(X, y):
    # Given a dataset of examples and labels, fit the weights of the logistic
    # regression classifier using the provided loss function and optimizer
    #
    # X := Tensor(float) of size (m,d) --- This is a batch of m examples of
    #     of dimension d
    #
    # y := Tensor(int) of size (m,) --- This is a batch of m labels in {-1,1}
    #
    # Return := Tensor of size (d,) --- This is the fitted weights of the
    #     logistic regression model
    import torch

    # Fill in the rest. Hint -- call optimize :-).
    return optimize(X,y,niters=100)

def logistic_predict(X, w):
    # Given a dataset of examples and fitted weights for a logistic regression
    # classifier, predict the class
    #
    # X := Tensor(float) of size(m,d) --- This is a batch of m examples of
    #    dimension d
    #
    # w := Tensor(float) of size (d,) --- This is the fitted weights of the
    #    logistic regression model
    #
    # Return := Tensor of size (m,) --- This is the predicted classes {-1,1}
    #    for each example
    #
    # Hint: Remember that logistic regression expects a label in {-1,1}, and
    # not {0,1}

    # Fill in the rest
    z=X@w
    return torch.where(z>=0,1,-1)

# Test your code on the wine dataset!
# How does your solution compare to a random linear classifier?
# Your solution should get around 75% accuracy on the test set.
torch.manual_seed(42)

d = X_train.size(1)
logistic_weights = {
    'zero': torch.zeros(d),
    'random': torch.randn(d),
    'fitted': logistic_fit(X_train, y_binary_train)
}

for k,w in logistic_weights.items():
    yp_binary_train = logistic_predict(X_train, w)
    acc_train = (yp_binary_train == y_binary_train).float().mean()

    print(f'Train accuracy [{k}]: {acc_train.item():.2f}')

    yp_binary_test = logistic_predict(X_test, w)
    acc_test = (yp_binary_test == y_binary_test).float().mean()

    print(f'Test accuracy [{k}]: {acc_test.item():.2f}')

grader.grade(test_case_id = 'logistic_loss', answer = getsource(logistic_loss))
grader.grade(test_case_id = 'logistic_gradient', answer = getsource(logistic_gradient))
grader.grade(test_case_id = 'logistic_fit', answer = getsource(logistic_fit))
grader.grade(test_case_id = 'logistic_predict', answer = getsource(logistic_predict))

"""# 2. Linear Regression with Ridge Regression (Optional, not graded)

In this second problem, you'll implement a linear regression model. Similarly to the first problem, implement the following functions:

1. Loss (3pts) - Given a batch of examples $X$ and labels $y$, compute the batched mean squared error loss for a linear model with weights $w$.
2. Fit (4pts) - Given a batch of examples $X$ and labels $y$, find the weights of the optimal linear regression model
3. Predict (3pts) - Given the weights $w$ of a linear regression model and new data $X$, predict the most likely label

This time, you are not given an optimizer for the fitting function since this problem has an analytic solution. Make sure to test your solution with non-zero ridge regression parameters.

Hint: You may want to review ridge regression on Slide 22 of Lecture 3.
"""

def regression_loss(X, y, w):
    # Given a batch of linear regression outputs and true labels, compute
    # the batch of squared error losses. This is *without* the ridge
    # regression penalty.
    #
    # X := Tensor(float) of size (m,d) --- This is a batch of m examples of
    #     of dimension d
    #
    # y := Tensor(int) of size (m,) --- This is a batch of m real-valued labels
    #
    # w := Tensor(float) of size(d,) --- This is the weights of a linear
    #     classifer
    #
    # Return := Tensor of size (m,) --- This is the squared loss for each
    #     example

    # Fill in the rest
    pass

def regression_fit(X, y, ridge_penalty=1.0):
    # Given a dataset of examples and labels, fit the weights of the linear
    # regression classifier using the provided loss function and optimizer
    #
    # X := Tensor(float) of size (m,d) --- This is a batch of m examples of
    #     of dimension d
    #
    # y := Tensor(float) of size (m,) --- This is a batch of m real-valued
    #     labels
    #
    # ridge_penalty := float --- This is the parameter for ridge regression
    #
    # Return := Tensor of size (d,) --- This is the fitted weights of the
    #     linear regression model
    #
    # Fill in the rest
    pass

def regression_predict(X, w):
    # Given a dataset of examples and fitted weights for a linear regression
    # classifier, predict the label
    #
    # X := Tensor(float) of size(m,d) --- This is a batch of m examples of
    #    dimension d
    #
    # w := Tensor(float) of size (d,) --- This is the fitted weights of the
    #    linear regression model
    #
    # Return := Tensor of size (m,) --- This is the predicted real-valued labels
    #    for each example
    #
    # Fill in the rest
    pass

# Test your code on the wine dataset!
# How does your solution compare to a random linear classifier?
# Your solution should get an average squard error of about 8.6 test set.
torch.manual_seed(42)

d = X_train.size(1)
regression_weights = {
    'zero': torch.zeros(d),
    'random': torch.randn(d),
    'fitted': regression_fit(X_train, y_regression_train)
}

for k,w in regression_weights.items():
    yp_regression_train = regression_predict(X_train, w)
    squared_loss_train = regression_loss(X_train, y_regression_train, w).mean()

    print(f'Train accuracy [{k}]: {squared_loss_train.item():.2f}')

    yp_regression_test = regression_predict(X_test, w)
    squared_loss_test = regression_loss(X_test, y_regression_test, w).mean()

    print(f'Test accuracy [{k}]: {squared_loss_test.item():.2f}')

grader.grade(test_case_id = 'regression_loss', answer = getsource(regression_loss))
grader.grade(test_case_id = 'regression_fit', answer = getsource(regression_fit))
grader.grade(test_case_id = 'regression_predict', answer = getsource(regression_predict))

"""### (Background) Gradients with PyTorch

At this point, you've implemented a lot of gradients. However, these days, manual implementation of gradients is a thing of the past: PyTorch is a scientific computing library that comes with the ability to automatically compute gradients for you! This is called auto-differentiation. Here is an example of using auto-differentiation to compute the gradient of a quadratic function, $f(x) = ax^2$. The key parts are as follows:

1. Variables that you want to differentiate with respect to should have the `requires_grad` flag set to `True`.
2. Calculate the objective that you'd like the compute the gradient of, using the variable from step (1).
3. Pass the objective and the variable you are differentiating to `torch.autograd.grad`.
"""

# Step 1: Set requires_grad to true for x
x = torch.Tensor([3.0])
a = torch.Tensor([1.5])
x.requires_grad = True

# Step 2: Compute the objective
y = a*(x**2)

# Step 3: Use autograd
grad = torch.autograd.grad([y],[x])[0]

print("PyTorch gradient:", grad)
print("Analytic gradient:", 2*a*x)

"""You'll notice that the gradient computed with PyTorch matches exactly the analytic gradient $\nabla f(x) = 2ax$, but without having to implement or derive the analytic gradient! This works for gradients with respect to any sized variables. For example, if $x$ is now a vector, and the objective is $f(x) = a\|x\|_2^2$ then we can calculate the gradient in the same way:"""

# Step 1: Set requires_grad to true for x
x = torch.Tensor([3.0, 2.0])
a = torch.Tensor([1.5])
x.requires_grad = True

# Step 2: Compute the objective
y = a*(x.norm(p=2)**2)

# Step 3: Use autograd
grad = torch.autograd.grad([y],[x])[0]

print("PyTorch gradient:", grad)
print("Analytic gradient:", 2*a*x)

"""From now on, we highly recommend that you use auto-differentiation to calculate gradients. As long as all of your operations are differentiable, the final objective will be differentiable.

# 3. SVM and Gradient Descent

In this first problem, you'll implement (soft margin) support vector machines with gradient descent, using gradients from PyTorch's autodifferentiation library.
+ (2pts) Calculate the objective of the Soft SVM
+ (2pts) Calculate the gradient of the Soft SVM objective
+ (2pts) Implement a basic gradient descent optimizer. Your solution needs to converge to an accurate enough answer.
+ (1pts) Make predictions with the Soft SVM

Tips:
- This assignment is more freeform than previous ones. You're allowed to initialize the parameters of the SVM model however you want, as long as your implemented functions return the right values.
- We recommend using PyTorch's `torch.autograd.grad` to get the gradient instead of deriving the SVM gradient.
- You'll need to play with the values of step size and number of iterations to
converge to a good value.
- To debug your optimization, print the objective over iterations. Remember that the theory says as long as the learning rate is small enough, for strongly convex problems, we are guaranteed to converge at a certain rate. What does this imply about your solution if it is not converging?
- As a sanity check, you can get around 97.5% prediction accuracy and converge to an objective below 0.16.
"""

class SoftSVM():
    def __init__(self, ndims):
        # Here, we initialize the parameters of your soft-SVM model for binary
        # classification. You can change the initialization but don't change
        # the weight and bias variables as the autograder will assume that
        # these exist.
        # ndims := integer -- number of dimensions
        # no return type

        self.weight = torch.randn(ndims)
        self.bias = torch.randn(1)
        self.weight.requires_grad = True
        self.bias.requires_grad = True

    def objective(self, X, y, l2_reg):
        # Calculate the objective of your soft-SVM model
        # X := Tensor of size (m,d) -- the input features of m examples with d dimensions
        # y := Tensor of size (m) -- the labels for each example in X
        # l2_reg := float -- L2 regularization penalty
        # Returns a scalar tensor (zero dimensional tensor) -- the loss for the model
        # Fill in the rest
        hinge_loss = torch.clamp(1-y*(X@self.weight+self.bias),min=0)
        loss = hinge_loss.mean() + l2_reg*(self.weight.norm()**2)
        return loss


    def gradient(self, X, y, l2_reg):
        # Calculate the gradient of your soft-SVM model
        # X := Tensor of size (m,d) -- the input features of m examples with d dimensions
        # y := Tensor of size (m) -- the labels for each example in X
        # l2_reg := float -- L2 regularization penalty
        # Return Tuple (Tensor, Tensor) -- the tensors corresponds to the
        # gradients of the weight and bias parameters respectively
        # Fill in the rest
        loss = self.objective(X,y,l2_reg)
        grad_weight , grad_bias = torch.autograd.grad(loss,[self.weight,self.bias])
        return grad_weight,grad_bias

    def optimize(self, X, y, l2_reg):
        # Calculate the gradient of your soft-SVM model
        # X := Tensor of size (m,d) -- the input features of m examples with d dimensions
        # y := Tensor of size (m) -- the labels for each example in X
        # l2_reg := float -- L2 regularization penalty

        # no return type

        # Fill in the rest
        for i in range(100):
          grad_weight,grad_bias = self.gradient(X,y,l2_reg)
          with torch.no_grad():
              self.weight -= grad_weight
              self.bias -= grad_bias

    def predict(self, X):
        # Given an X, make a prediction with the SVM
        # X := Tensor of size (m,d) -- features of m examples with d dimensions
        # Return a tensor of size (m) -- the prediction labels on the dataset X

        # Fill in the rest
        return torch.where((X @ self.weight+self.bias)>=0,1,-1)

"""Test the Soft SVM on the breast cancer dataset:"""

#Load dataset
cancer = datasets.load_breast_cancer()
X,y = torch.from_numpy(cancer['data']), torch.from_numpy(cancer['target'])
mu,sigma = X.mean(0,keepdim=True), X.std(0,keepdim=True)
X,y = ((X-mu)/sigma).float(),(y - 0.5).sign() # prepare data
l2_reg = 0.1
print(X.size(), y.size())

# Optimize the soft-SVM with gradient descent
clf = SoftSVM(X.size(1))
clf.optimize(X,y,l2_reg)
print("\nSoft SVM objective: ")
print(clf.objective(X,y,l2_reg).item())
print("\nSoft SVM accuracy: ")
(clf.predict(X) == y).float().mean().item()

grader.grade(test_case_id = 'SVM_objective', answer = get_class_source(SoftSVM))
grader.grade(test_case_id = 'SVM_gradient', answer = get_class_source(SoftSVM))
grader.grade(test_case_id = 'SVM_optimize', answer = get_class_source(SoftSVM))
grader.grade(test_case_id = 'SVM_predict', answer = get_class_source(SoftSVM))